In [2]:
#Calling built-in functions
my_string = 'Hello'
type(my_string)
print(my_string)

Hello


In [4]:
len(my_string)
print(my_string)

Hello


In [18]:
#Functions vs methods
integers = [0,1,2,3,4]

In [19]:
integers.append(-1)

In [20]:
print(integers)

[0, 1, 2, 3, 4, -1]


In [21]:
sorted(integers)

[-1, 0, 1, 2, 3, 4]

In [22]:
print(integers)

[0, 1, 2, 3, 4, -1]


In [25]:
integers = sorted(integers)
print(integers)

[-1, 0, 1, 2, 3, 4]


In [26]:
integers = [0,1,2,3,4]
integers.append(-1)

In [27]:
print(integers)

[0, 1, 2, 3, 4, -1]


In [38]:
integers.sort()
print(integers)

[-1, 0, 1, 2, 3, 4]


In [39]:
help(list.sort)

Help on method_descriptor:

sort(self, /, *, key=None, reverse=False)
    Sort the list in ascending order and return None.
    
    The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
    order of two equal elements is maintained).
    
    If a key function is given, apply it once to each list item and sort them,
    ascending or descending, according to their function values.
    
    The reverse flag can be set to sort in descending order.



In [42]:
#Defining functions

def my_function(arg1, arg2):
    '''This is a docstring'''
    #this is a body of the function
    output1=0
    output2=1
    return output1, output2

my_function(5,6)

(0, 1)

In [43]:
help(my_function)

Help on function my_function in module __main__:

my_function(arg1, arg2)
    This is a docstring



In [45]:
%time my_function(5,6)

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 9.06 µs


(0, 1)

In [55]:
#Function to calculate the hypotenuse side of a right triangle with sides a and b
def pythagoras(a,b):
    '''Calculates the hypotenuse side of a right triangle with sides a and b
    
    Input arguments: 
    a: (float) a side length
    b: (float) a perpendicular side length

    Returns:
    c: (float) the hypotenuse side length
    '''
    if a>0 and b>0:
        c = (a**2 + b**2)**0.5
        return c
    else:
        print('The side lengths must be larger than 0')
        return None

In [47]:
help(pythagoras)

Help on function pythagoras in module __main__:

pythagoras(a, b)
    Calculates the hypotenuse side of a right triangle with sides a and b
    
    Input arguments: 
    a: (float) a side length
    b: (float) a perpendicular side length
    
    Returns:
    c: (float) the hypotenuse side length



In [56]:
pythagoras(3,4)

5.0

In [57]:
pythagoras(0,4)

The side lengths must be larger than 0


In [58]:
#Consistency check
pythagoras(1,1) == 2**0.5

True

In [59]:
#Global vs local variables

a = 3 #global value of a

def my_function():
    a = 10
    print(a)

my_function()

10


In [60]:
print(a)

3


In [61]:
x = 5

def function(y,z):
    y, z = 0, 0 
    print(x)

function(1, 2)

5


In [62]:
def countdown(n):
    '''Recursive function that counts down from a positive n to zero'''
    
    #print current value of n
    print(n)
    
    #if you get to zero, you return nothing
    if n == 0:
        return None
    else:
        return countdown(n-1)

In [64]:
countdown(3)

3
2
1
0


In [83]:
#Importing libraries
import math
import numpy as np
import matplotlib
import os
import pandas
import scipy

In [90]:
math.pi

3.141592653589793

In [91]:
math.cos(math.pi)

-1.0

In [92]:
math.factorial(6)

720

In [93]:
math.sqrt(4)

2.0

In [94]:
from math import sqrt
sqrt(4)

2.0

In [95]:
#Using numpy
import numpy as np

In [98]:
my_list = [1,2,3]
my_array = np.array([1,2,3])
print(my_list, my_array)

[1, 2, 3] [1 2 3]


In [100]:
type(my_array)

numpy.ndarray

In [101]:
print(3*my_list, 3*my_array)

[1, 2, 3, 1, 2, 3, 1, 2, 3] [3 6 9]


In [102]:
another_list = [0,0,1]

In [103]:
my_list+another_list

[1, 2, 3, 0, 0, 1]

In [104]:
my_array+np.array(another_list)

array([1, 2, 4])

In [106]:
#Working with vectors
v_1 = np.array([0,1,2])
print(v_1)

[0 1 2]


In [112]:
v_2 = np.array([1,1,1])
print(v_2)

[1 1 1]


In [111]:
v_1*v_2

array([0, 2, 4])

In [116]:
v_1.dot(v_2)

np.int64(3)

In [123]:
float(v_1.dot(v_2))

3.0

In [124]:
np.dot(v_1, v_2).item()

3

In [125]:
np.linspace(0,2,3, dtype = int)

array([0, 1, 2])

In [128]:
np.linspace(0,2, num = 3, dtype = int)

array([0, 1, 2])

In [129]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly s